services:
  - type: web
    name: carbon-pictograms-svelte
    env: static
    buildCommand: yarn; yarn prepack; cd preview; yarn; yarn build
    staticPublishPath: preview/build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
